### ISSUE TITLE
AGM-154C incorrect listing name

### ISSUE THREAD

**Issue by Temeter** [spencershepard/DCS-Scripts#11]
In the 'explTable', the AGM-154C is incorrectly listed as:  ["AGM_154C"]  = 305

This is reflected by the missing AoE effect and log warning:

2023-04-29 14:45:59.940 INFO    SCRIPTING (Main): AGM_154 missing from Splash Damage script

Renaming the the list entry to ["AGM_154"] fixed the issue, and the weapon now does the correct AoE effect.

As a disclaimer, the CBU based 154 uses the name [AGM-154A]

**Comment by spencershepard** [comment]
fixed with #13
